sed -i 's/gbc-secondary-text-color/theme-primary-color/' theme.scss.json
sed -i 's/gbc-primary-color/theme-primary-background-color/' theme.scss.json
sed -i 's/gbc-primary-medium-color/theme-primary-emphasis-background-color/' theme.scss.json
sed -i 's/gbc-primary-light-color/theme-primary-faded-background-color/' theme.scss.json
sed -i 's/gbc-primary-background-color/theme-secondary-background-color/' theme.scss.json
sed -i 's/gbc-secondary-background-color/theme-secondary-alternative-background-color/' theme.scss.json
sed -i 's/gbc-field-background-color/theme-field-background-color/' theme.scss.json
sed -i 's/gbc-header-color/theme-header-color/' theme.scss.json
sed -i 's/gbc-separator-color/theme-separator-color/' theme.scss.json
sed -i 's/gbc-disabled-color/theme-disabled-background-color/' theme.scss.json
sed -i 's/gbc-field-disabled-background-color/theme-field-disabled-background-color/' theme.scss.json
sed -i 's/gbc-message-color/theme-message-background-color/' theme.scss.json
sed -i 's/gbc-error-color/theme-error-background-color/' theme.scss.json
sed -i 's/gbc-field-height-ratio/theme-field-height-ratio/' theme.scss.json
sed -i 's/gbc-font-size-ratio/theme-font-size-ratio/' theme.scss.json
sed -i 's/gbc-margin-ratio/theme-margin-ratio/' theme.scss.json
sed -i 's/gbc-radiobutton-size/theme-radiobutton-size/' theme.scss.json
sed -i 's/gbc-checkbox-size/theme-checkbox-size/' theme.scss.json
sed -i 's/gbc-sidebar-always-visible-min-width/theme-sidebar-always-visible-min-width/' theme.scss.json
sed -i 's/gbc-sidebar-default-width/theme-sidebar-default-width/' theme.scss.json
sed -i 's/gbc-animation-duration/theme-animation-duration/' theme.scss.json
sed -i 's/gbc-desactivate-ending-popup/theme-disable-ending-popup/' theme.scss.json
