#!/bin/sh

### BEGIN INIT INFO
# Provides:	  flm
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Genero License Manager
# Description: Service for managing Genero Licenses
### END INIT INFO

FLMPID=/var/run/flm.pid

. /opt/fourjs/flm/envflm

. /lib/lsb/init-functions

case $1 in
	start)
		#echo $( date ) "$FLMDIR/bin/flmprg -r starting ..." 
		echo $( date ) "$FLMDIR/bin/flmprg -r starting ..." >> /var/log/flm.log
		if ! start-stop-daemon --start --exec $FLMDIR/bin/flmprg --pidfile $FLMPID -- -r
		then
			log_end_msg 1
			exit 1
		else
			PID=$(ps wax | grep "[Ff]lmprg" | cut -c1-6 )
			echo $PID > $FLMPID
		fi
		;;
	stop)

		echo $( date ) "flmprg stopping ..." >> /var/log/flm.log
		log_daemon_msg "Stopping FLM" flm

		start-stop-daemon --stop --quiet --pidfile $FLMPID
		# Wait a little and remove stale PID file
		sleep 1
		if [ -f $FLMPID ] && ! ps h `cat $FLMPID` > /dev/null
		then
			# Stale PID file (flm was succesfully stopped),
			# remove it (should be removed by flm itself IMHO.)
			rm -f $FLMPID
		fi

		log_end_msg 0

		;;
	restart|force-reload)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		status_of_proc -p $FLMPID $FLMDIR/bin/flm flm
		exit $?
		;;
	*)
		echo "Usage: /etc/init.d/flm {start|stop|restart|force-reload|status}"
		exit 1
		;;
esac

exit 0
